version: '3.0'
services:
   mysql:
     build:
       context: .
       dockerfile: Dockerfile-mysql
     image: notweibo/mysql
     ports:
       - "3306:3306"
     volumes:
           - /docker/notweibo/mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: c0nygre

   app:
     build:
       context: .
       dockerfile: Dockerfile-app
     image: notweibo/app
     ports:
       - "8081:8080"
     links:
       - mysql:mysql
     depends_on:
       - mysql
